import os
os.system('cls')
game_over = "\n*********\nGAME OVER\n*********\n\n"
press_enter = "Press 'Enter' to continue. "

# treasure chest from https://ascii.co.uk/art/treasureisland by ejm97
print("")
print("         __________")
print("        /\\____;;___\\")
print("       | /         /")
print("       `. ())oo() .")
print("        |\\(%()*^^()^\\")
print("       %| |-%-------|")
print("      % \\ | %  ))   |")
print("      %  \\|%________|")
print("\nWELCOME TO TREASURE ISLAND!\n")
print("Welcome explorer. This is Treasure Island.")
print("A choose your own adventure type game, where your goal is to find some treasure.")
input(press_enter)
os.system('cls')

print("\nYou find yourself in the center of a deserted island.")
print("This island was once inhabited, but now seems to just be ruins.")
print("You've been walking for ages, and haven't seen another person.\n")
print("As you follow the path you find yourself on, you come to a crossroads.")
print("The path splits, neither route giving a clue as to what lies ahead.")
choice = input("Do you want to take the path to 'Left' or 'Right'? ").capitalize()
os.system('cls')
if choice == "Right":
    
    print("\nThe path slowly narrows, and you begin to find yourself struggling through leaves and vines,")
    print("small thorns snagging and tugging and tearing at your clothes.\n")
    print("Suddenly, you feel the ground open beneath you and quickly find yourself staring up")
    print("from the bottom of a deep cavernous pit with completely smooth walls.")
    print("\nYou hope someone will come by to help you out, but for now this is...")
    print(game_over)
    quit()
elif not choice == "Left":
    print("\nYou don't need a path to stick to - you can make your own path!")
    print("You leave the trail and forge your own way.")
    input(press_enter)
    os.system('cls')
    print("Or.. at least you thought you could.")
    print("\nAs you continue to wander aimlessly through a vast jungle, you quickly find yourself lost.")
    print("The vines and leaves and thorns and roots seem to get increasingly thicker, pulling at you.")
    print("This goes on for hours, and the way seems to get more difficult with each step until finally,")
    print("with a great deal of frustration, you decide to sit down for a moment to get your bearings.")
    print("\nYou quickly find you're completely lost, with no clue where you are.")
    print("The vines seem to reach out towards you. Their thorns dig into your skin. You feel your eyelids grow heavy.")
    print("You just need a short rest...")
    input(press_enter)
    os.system('cls')
    print("\nHowever, this jungle is unforgiving, and you never wake up.")
    print(game_over)
    quit()

print("\nAfter treking through the jungle for hours, you finally see a break in the vegetation.")
print("Cautiously, you approach, hearing the sounds of running water.")
print("It's a river!")
print("It's hard to tell just how deep it is, but it looks pretty slow moving...")
choice = input("Do you want to 'Search' for a raft, or just 'Wade' across? ").capitalize()
os.system('cls')

if not choice == "Search":
    print("\"It doesn't look that dangerous,\" you say to yourself as you step off the bank.")
    print("Your shoes slosh the first few steps as you step into the murky water.")
    print("Quickly, the water is up to your thighs, when you feel movement under the surface.")
    print("It happens so fast, you almost don't have time to react! You feel a jolt of fear")
    print("as you see the first eel leap from the water at you.")
    input(press_enter)
    os.system('cls')
    print("The eels leap at you. One at a time at first, then many.")
    print("Under the water, you feel their tiny mouths taking small, sharp bites.")
    print("You rush towards the far bank, moving deeper into the water.")
    input(press_enter)
    os.system('cls')
    print("As you go deeper, the eel's numbers seem to multiply.")
    print("You slip beneath the surface, which froths for a moment, then returns to a calm, placid state.")
    print(game_over)
    quit()

print("You look up and down the bank, not wanting to step into murky water.")
print("After a few moments, you find an old raft, and push it into the water.")
print("You quickly float across to the other side. Then hike back up to where the path continues.")
input(press_enter)
os.system('cls')

print("You continue hiking and eventually come across an old decrepit temple.")
print("\nAs you step up, you see three intricately carved doors.")
print("First, you see a 'Red' door, with carvings of fire on it.")
print("Second, you see a 'Yellow' door, with a carving of the sun.")
print("Third, you see a 'Blue' door, with a depiction of waves, or maybe the ocean.")
input(press_enter)
os.system('cls')

print("\nAs you move closer to inspect the doors, you hear movement from behind you.")
print("You turn to look and a jaguar is quickly running at you! You need to choose a door!")
choice = input("With only a second left before your demise, which door do you enter? \n'Red', 'Yellow', or 'Blue'? ").capitalize()
os.system('cls')

if choice == "Red":
    print("With only a second remaining, you reach out for the Red door.")
    print("You reach for the handle, and fling the door open.")
    print("As you pull, time seems to slow, and it gives you time to study the carving.")
    print("Fire erupts from the door incinerating both you and the big cat.")
    print(game_over)
    quit()
elif choice == "Yellow":
    print("You spin back and crash into the Yellow door, slamming it shut behind you.")
    print("Breathing heavy, you take in your surroundings.")
    print("Sunlight glitters in your vision as your eyes go wide, taking in the mountain of gold.")
    print("You've found your treasure, and even better, you see a boat on the shore ready to take you home.")
    print("\nCongratulations!")
    print("You win!")
    quit()
elif choice == "Blue":
    print("You throw your back against the blue door and push.")
    print("It slowly creaks open, but not quickly enough.")
    print("The jaguar slams into you and.. well..")
    print(game_over)
    quit()
else:
    print("You- you decided to not go through one of the doors?")
    print("I.. okay..")
    print("\nThe jaguar eats you. That's it.")
    print(game_over)
    quit()

